spring:
  application:
    name: chatgpt-server

  datasource:
    url: jdbc:mysql://yourMysql/chatgpt?createDatabaseIfNotExist=true
    # url: jdbc:mysql://mysql-container:3306/chatgpt?createDatabaseIfNotExist=true
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

server:
  port: 8080